# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "D ã® Java"
subtitle: "åˆ«æ€•è·¯é•¿æ¢¦è¿œ"
description: "æ¬¢è¿æ¥æˆ‘çš„åšå®¢ç©ºé—´"
keywords: "java,web,c"
author: "D"
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://pigpigletsgo.github.io
root: /
permalink: :title/ # edit for Theme.shoka
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false # edit for Theme.shoka
  line_number: true
  auto_detect: true
  tab_replace: ''
prismjs:
  enable: false # edit for Theme.shoka

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  è®¡ç®—æœºå­¦ç§‘: computer-science
  æ•°æ®ç»“æ„ä¸ç®—æ³•: data-structures-and-algorithms
  ç¼–ç¨‹é¢˜: programming-questions
  Java: java
  js: js
  web: web
  video: video
  movie: movie
  Tvdrama: Tvdrama
  animation: animation
  Reality: Reality
  é—®é¢˜æ€»æ±‡: bug
  css: css
  vue: vue
  vue3: vue3
  database: databse
  mongodb: mongodb
  mysql: mysql
  hexo: hexo
  shoka: shoka
  ç§»åŠ¨ç«¯: ç§»åŠ¨ç«¯
  æ¡ˆä¾‹ä»£ç : æ¡ˆä¾‹ä»£ç 
  ECMASCript: ECMASCript
  WebAPIs: WebAPIs
  JSè¿›é˜¶: JSè¿›é˜¶
  æ­£åˆ™: æ­£åˆ™
  redis: redis
  JDBC: JDBC
  tools: tools
  æ¡ˆä¾‹Demo: æ¡ˆä¾‹Demo
  è®¾è®¡æ¨¡å¼: è®¾è®¡æ¨¡å¼
  C: C
  spring: spring
  math: math
  english: english
  JVM: JVM
  çŸ¥è¯†ç‚¹: çŸ¥è¯†ç‚¹
  git: git
  å‰åç«¯äº¤äº’: å‰åç«¯äº¤äº’
  websocket: websocket
  linux: linux
  nginx: nginx
tag_map:

search:
  enable: true
  path: search.json # search.xml
  field: post
  format: html
  limit: 10000
  content: true
  unescape: true  
  preload:  true  
  trigger: "auto" 
  pageSize: 10

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: shoka # edit for Theme.shoka

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# edit for Theme.shoka
autoprefixer:
  exclude:
    - '*.min.css'

markdown:
  render: # æ¸²æŸ“å™¨è®¾ç½®
    html: false # è¿‡æ»¤ HTML æ ‡ç­¾
    xhtmlOut: true # ä½¿ç”¨ '/' æ¥é—­åˆå•æ ‡ç­¾ ï¼ˆæ¯”å¦‚ <br />ï¼‰ã€‚
    breaks: true # è½¬æ¢æ®µè½é‡Œçš„ '\n' åˆ° <br>ã€‚
    linkify: true # å°†ç±»ä¼¼ URL çš„æ–‡æœ¬è‡ªåŠ¨è½¬æ¢ä¸ºé“¾æ¥ã€‚
    typographer:
    quotes: 'â€œâ€â€˜â€™'
  plugins: # markdown-itæ’ä»¶è®¾ç½®
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # æ–‡ç« ç›®å½•ä»¥åŠé”šç‚¹åº”ç”¨çš„classåç§°ï¼Œshokaä¸»é¢˜å¿…é¡»è®¾ç½®æˆè¿™æ ·
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "ä½ çŸ¥é“å¾—å¤ªå¤šäº†"

minify:
  html:
    enable: true
    stamp: false
    exclude:
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    stamp: false
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    stamp: false
    mangle:
      toplevel: true
    output:
    compress:
    exclude:
      - '**/*.min.js'

valine:
  appId: wdsNlBUj9JciEmqYqF8X7rSK-gzGzoHsz
  appKey: sxgx5PvvR9JDk4fEhCYX8muE
  placeholder: "ãƒ½(â—‹Â´âˆ€`)ï¾‰â™ª ~~~ å¿«æ¥è¯„è®ºæŠŠï¼Œä½¿ç”¨è¯´æ˜å¦‚ä¸‹ï¼š\nğŸ’¥1.åå­—éšä¾¿å¡«å†™\nğŸ“¸2.è¾“å…¥è‡ªå·±çš„QQé‚®ç®±\nğŸ’£3.ç½‘ç«™å¯ä»¥ä¸å¡«å†™\nâš¡å‰ä¸¤ä¸ªå®Œæˆåå°±å¯ä»¥è¯„è®ºå•¦!!!" # Comment box placeholder
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # Pagination size
  lang: zh-CN
  visitor: true # Article reading statistic
  NoRecordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  powerMode: true
  tagMeta:
    visitor: æ–°æœ‹å‹
    master: ä¸»äºº
    friend: å°ä¼™ä¼´
    investor: é‡‘ä¸»ç²‘ç²‘
  tagColor:
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
    investor: "var(--color-pink)"
  tagMember:
    master:
      # - hash of master@email.com
      # - hash of master2@email.com
    friend:
      # - hash of friend@email.com
      # - hash of friend2@email.com
    investor:
      # - hash of investor1@email.com


# algolia:
#   appId:
#   apiKey:
#   adminApiKey:
#   chunkSize: 5000
#   indexName:
#   fields:
#     - title #å¿…é¡»é…ç½®
#     - path #å¿…é¡»é…ç½®
#     - categories #æ¨èé…ç½®
#     - content:strip:truncate,0,4000
#     - gallery
#     - photos
#     - tags

feed:
    limit: 20
    order_by: "-date"
    tag_dir: false
    category_dir: false
    rss:
        enable: true
        template: "themes/shoka/layout/_alternate/rss.ejs"
        output: "rss.xml"
    atom:
        enable: true
        template: "themes/shoka/layout/_alternate/atom.ejs"
        output: "atom.xml"
    jsonFeed:
        enable: true
        template: "themes/shoka/layout/_alternate/json.ejs"
        output: "feed.json"

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:PigPigLetsGo/PigPigLetsGo.github.io.git
  branch: main